[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
password_escrow = "FZrLq9ehNww5jnGkZ3suXiwUGJtg6socYadSPWYhFgUS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/btolfa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
